<?php

namespace CarteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DieuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DieuRepository extends EntityRepository
{
}
