<?php

namespace CarteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ExtensionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtensionRepository extends EntityRepository
{

    public function findAll()
    {
        return $this->findBy(array(), array('date' => 'DESC'));
    }
}
