creation_dieu:
    path: /dieu/creation
    defaults: { _controller: CarteBundle:Dieu:creationDieu }

creation_carte:
    path: /carte/creation
    defaults: { _controller: CarteBundle:Carte:creationCarte }

creation_carte_ext:
    path: /carte/creation/{idExt}
    defaults: { _controller: CarteBundle:Carte:creationCarteExt }

creation_extension:
    path: /extension/creation
    defaults: { _controller: CarteBundle:Carte:creationExtension }

liste_dieux:
    path: /dieu/liste
    defaults: { _controller: CarteBundle:Dieu:affichageListeDieux }

liste_cartes:
    path: /carte/liste
    defaults: { _controller: CarteBundle:Carte:affichageListeCartes }

liste_extensions:
    path: /extension/liste
    defaults: { _controller: CarteBundle:Carte:affichageListeExtension }

affichage_extension:
    path: /extension/affichage/{idExt}
    defaults: { _controller: CarteBundle:Carte:affichageExtension }

liste_extension_perso:
    path: /extension/liste_perso
    defaults: { _controller: CarteBundle:Carte:affichageListeExtensionPerso }

supprimer_carte:
    path: /carte/supprimer/{idCarte}
    defaults: { _controller: CarteBundle:Carte:supprimerCarte }

supprimer_extension:
    path: /extension/supprimer/{idExt}
    defaults: { _controller: CarteBundle:Carte:supprimerExtension }

valider_carte:
    path: /carte/validation
    defaults: { _controller: CarteBundle:Carte:validerCarte }
    requirements:
      _method: POST

